language: ruby
rvm:
- 2.1.6
script:
- bundle exec rake --trace
before_deploy:
- bundle exec rake after_build --trace
deploy:
  provider: rubygems
  gem: stash-api
  api_key:
    secure: CegY+uW3doi70aBYv+M/+3eYUPuu0trMaOf8puKwYWQkDpz9iw2M0NenOA22RIkbUwLUzrawr1AVRN1U5iMyMEjNJM/kcWz7uQOqxlvd0m+e1w4QgZeiOc2V7TGrD8SsgDliiOhULqB8Rerl8Ja06S390aetZg8nf7EKpNul0yTxsfh4i+v3WZFYnKUStWuawI+2ckEjD7vLJg7ot15eBJBDPkvN6Uv47fE7rwcitGPJttuneK1oDryTBBVlLQKsPOBIeF5eH4wYpegnvxEdPMnmxumaPtL0J6jW4QRpjMtTd1bVWJVCaLojkbXhprz/RdOetDJYIIVmhVbrF6TWsI+Ga90i0Ww7sAJmEqVoGXh7KdWmhWANKPFZDgWRMDFuHd8Fxame+VnnsdDXHHaZxvVPcBbasdLaIB0ae8eDEtp3/8NV5gyonXIyTDa67JBJ78WxURfm0fsjBWUvwdwKe7Na93zjtTd2KPXXMrAqBzqkD3DHxbVyFeiRKdcETqg1FZ0nGbb+H9CdhCfq/Iee23shVYdd4CcB7Cy5JPblYbjltsk+2WSO+QuHqa6tphbNKeE70en3X8NXRr9DbWpng5XADkmcnCOo0juosXv+OJEUR9t+qg21uF8pyOCbX4SnHF5oVLbossSptDVs9W5yR4sVYoavExycr6HQWx1dxmc=
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  only:
  - master
  - /^release.*/
env:
  global:
  - secure: Z/MEwKpThF3K1i1u1u418dwIbIgjXeFU/GxXDGzquuIot5q3Z0E/9po/zAD3WXlBLXA9f9uArxl/vBtCq8i12kf5UC9eloWj1EtXgDf5XhRcDT6dXIo4Fz0Tmwbelge1suPSDFZGFyxwVHI5Ns185Ya7qQmxY5HwicXUtCv0Cb+G6G3cn56sikz+SVrfv9czbENhVu0r2uuP959n2NHuzKmjXkDcPd4mJtP0/As7ZHRYjeJvJdvZ0Q5Vg78pGRBssvKvrt3Tcar2Di3R+Rmn3rw3UlynMwqgbkHlf7Rge3CPhYtN0t0+6cmduzgn8XQW+MBANA+qAcfIYpKVVRCuPfjsAY6BrxXPfal7nlULyiV7kPjMZnTLA6uIBFyzdG7VstF+XGUdb4diZfzAWpFKC/vUSgZ8K/goj1CgCkwZHYMbH6qhx1EEtj8uGpw0qei+SJjA6b3dC5xp1fosDcqCUBb+sTeNJ5vutLnZfjnh075d8fKUVmdYH/z88ArJPvgU4F/cnliVvqKSAZfHgZsgSWtQ9T+ec0nd5ZjSFthfRXQIuecxrlhenGRcsBxtCy4JnCz3Ni3+Bdks2Bdyfh+84H+cg69fTUKCrHQzJ9PX9pgSLOX+hcCSTWYpsJaWaATBcN6Fsfi38cYMimwESqFkeechblga2Jgv5LZ1dKqsJ2U=
